version: "3.9"
services:

  resource-registry-init:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: resource-registry-init
    volumes:
      - "./RACK2022.xlsx:/RACK2022.xlsx"
    environment:
      SLM_HOST: "http://192.168.153.47"
      SLM_USER: "fabos"
      SLM_PASSWORD: "password"
      XLSX_FILE: "/RACK2022.xlsx"
      SHEET_NAME: "DEVICES"
      FORCE_OVERWRITE: "False"
      FORCE_DELETE: "False"
      DELETE_ALL: "False"
      PING_CHECK: "False"



